### ISSUE TITLE
Интеграция с 1С Предприятие

### ISSUE THREAD

**Issue by Coolagin** [ohmycto/synergy#13]
Хотелось бы узнать на каком этапе находится разработка обмена с 1С.?

**Comment by ohmycto** [comment]
Смотря какую конфигурацию 1С вы имеете ввиду? Если с 1С 7.7, то первый релиз запланирован на конец Июля - начало Августа, т.е в течение ближайших 10-15 дней. 

Правда, пока не решено, будет ли этот компонент бесплатным или платным. Даже если он будет платным, вполне возможно первые beta-тестеры получат его бесплатно в обмен на фидбек. Если у вас есть интерес в этом, пожалуйста, дайте знать.

Что касается интеграции с 8-кой, то там гораздо более сложная задача, т.к. в планах настоящая real-time интеграция через API-платформы, поэтому ожидать ее стоит скорее осенью.

**Comment by Coolagin** [comment]
Ну меня интересовала 8.*Так что будем ждать осени.
Если нужна помощь по 1С  обращайтесь.

**Comment by snesterov** [comment]
я могу потестить 1с 7.7 )))

**Comment by ohmycto** [comment]
Сергей, насколько я понимаю, с вами как раз договоренность уже достигнута, вы его и так получите бесплатно :)

**Comment by snesterov** [comment]
Спасибо Денис:)

**Comment by Shalnov** [comment]
Просветите пожалуйста, интеграция с 1С Предприятие с чем?

**Comment by ohmycto** [comment]
Не очень понял ваш вопрос? Речь про интеграцию 1С и Synergy.

**Comment by Shalnov** [comment]
Спасибо большое secoint. Разобрался. Я просто пока плохо ориентируюсь в github.

**Comment by Sashe** [comment]
И каков результат? Гем есть или нет?

**Comment by ohmycto** [comment]
Пока в стадии закрытого тестирования.

**Comment by Sashe** [comment]
А можно тоже поучаствовать?

**Comment by ohmycto** [comment]
Скорее всего модуль сопряжения с 1С не будет в свободном доступе, т.к. он состоит из 2-х частей: модуля импорта\экспорта на стороне магазина и обработки на стороне 1С.
Тестирование уже почти закончено, если вас интересует приобретение модуля, напишите на synergy@secoint.ru.

**Comment by dapi** [comment]
А почему вы не воспользовались стандартными механизмами импорта/экспорта 1С? Я про CommerceML

**Comment by Sashe** [comment]
А можно поподробнее? Как связать эту штуку с synergy?

**Comment by Coolagin** [comment]
В 1с есть типовая выгрузка!Выгружаешь CommerceML(формат сатаны) , ну а остальное за малым , парсим и загружаем!Почему бы просто то что выгружается в Bitrix не разобрать и загрузить  в Spree?

**Comment by ohmycto** [comment]
1С 7.7 умеет выгружать CommerceML из коробки? В общем, это уже не так важно, мы изначально не планировали связываться с 7-й версией, данный модуль появился скорее как сопутствующий продукт.

**Comment by Coolagin** [comment]
Забыл уточнить что я имел ввиду версию 8.*!Насчет 77 я не в курсе
