### ISSUE TITLE
Не могу установить, всегда 404 

### ISSUE THREAD

**Issue by Pyatka-Ubiyca** [ohmycto/synergy#14]
Сделал. все по инструкции, вроде бы ошибок не возникало. в итоге обращаюсь  http://fermashop.sapeens.locum.ru/
и 404.   база  частично заполнилась данными , Страны, штаты.. еще что-то.. 

все вроде бы нормально. но всегда выдает 404 :(

shared-Хостинг locum.ru,  может там со стороны веб сервера какие-то проблемы..

**Comment by romul** [comment]
Проблема не связана с Synergy.
Решено тут http://groups.google.com/group/synergy-user/browse_thread/thread/f494a805259eb3e5
