### ISSUE TITLE
Торг-12 и прочее

### ISSUE THREAD

**Issue by proton** [ohmycto/synergy#15]
Хотелось бы получить возможность генерировать подобные документы, есть ли в планах?

**Comment by ohmycto** [comment]
В настоящий момент существует расширение "Работа с юр. лицами", которое позволяет автоматизированно выставлять счета клиентам юридическим лицам. Массовой потребности в ТОРГ-12 нет, т.к. в основном владельцы магазинов все равно ведут учет в какой-либо внешней программе и выставляют документы оттуда. 

Вы можете предложить идею сюда (http://synergy.reformal.ru/), если она найдет поддержку среди других пользователей, то вполне возможно мы включим ТОРГ-12 в следующие релизы.

Если у вас есть возможность и желание помочь проекту, вы можете взять на себя этот кусок работы или профинансировать его, купив расширение "работа с юр. лицами".

**Comment by proton** [comment]
где можно увидеть возможности и стоимость расширения?

**Comment by ohmycto** [comment]
В настоящий момент возможности расширения следующие:
1. В конфигурации магазина добавляется группа настроек для автоматизации работы с юр. лицами (данные владельца магазина - наименование организации, ИНН\КПП, расч. счет, настройки НДС и т.п.).
2. Зарегистрированные клиенты могут указать признак "Юридическое лицо" в своем профиле. При этом им нужно будет также заполнить данные о своей организации.
3. Для юридического лица доступны все методы доставки, кроме Наложенного платежа.
4. Для юридического лица доступен только один метод оплаты - "Счет для юридических лиц". Для остальных наоборот, он недоступен.
5. На шаге подтверждения заказа в новом окне выводится печатная форма стандартного счета на оплату, номер которого совпадает с номером заказа.
6. В личном кабинете в списке заказов можно распечатать счет повторно.

Стоимость интеграции наши расширения в ваш магазин 10 000 рублей.

Также отдельно существует связка с 1С 7.7, которая позволяет выгружать данные о заказах из магазина, которые превращаются в документы "Счет", пригодные для дальнейшей обработки (в т.ч. для формирования ТОРГ-12 и т.п.).

**Comment by proton** [comment]
Спасибо за информацию

**Comment by impedance** [comment]
Если кто-нибудь купит у вас это расширение, он может потом его выложить для сообщества?
