### ISSUE TITLE
Слетает настройка «использовать SSL на продакшне»

### ISSUE THREAD

**Issue by yevgeny** [ohmycto/synergy#16]
При перезагрузке приложения настройка allow_ssl_in_production становится false.

Rails 3.0.9
sqlite3
RAILS_ENV=production

---

1) Ставлю галку «SSL шифрование будет включено в режиме production».
2) Делаю touch tmp/restart.txt.
3) В админку вход по незащищенному соединению.
В разделе общей конфигурации написано «SSL шифрование НЕ будет включено в режиме production».

<code>sqlite> select name, value from preferences where name = 'allow_ssl_in_production';
allow_ssl_in_production|f</code>

Должно быть:
<code>allow_ssl_in_production|1</code>

**Comment by romul** [comment]
Всё верно, эту настройку придётся задать в site-extension activate... Т.к. [она задана в false](https://github.com/secoint/synergy/blob/master/lib/synergy.rb#L40) из-за бесконечных жалоб новичков на то, что они не могут зайти в админку.
