### ISSUE TITLE
Отключение кеширования

### ISSUE THREAD

**Issue by jalkoby** [ohmycto/synergy#17]
При использовании synergy, заметил не очень приятную вещь. Если есть отображение таксономии на главной страницы и изменить таксономию для продукта, изменения на новой странице не отобразяться сразу. Только когда удаляяешь кеш из папки tmp, главная страница обновляеться. Можно ли отключить кеширование в настройках в веб интерфейсе или инициализаторах?

**Comment by romul** [comment]
Вы можете отключить кеширование в настройках своего приложения: config/environments/production.rb
Но лучше, настройте подключение к memcached через dalli. То, что в production режиме происходит кеширование в tmp, свидельствует о неполной настройке production-сервера.
