### ISSUE TITLE
Мигрировать базы

### ISSUE THREAD

**Issue by Sashe** [ohmycto/synergy#18]
Развернул проект на VPS Hetzner, вроде получилось. Связка nginx + Phusion Passenger + MySQL. Всё вроде запустилось и работает. Как базы мигрировать? Ну, там я таксономии добавил в девелопменте, пару товаров и прочее. Какова вообще правильная процедура?

**Comment by romul** [comment]
Для вопросов есть группа: http://groups.google.com/group/synergy-user

**Comment by Sashe** [comment]
Спасибо, разместил вопрос там!
