### ISSUE TITLE
Проблемы при установке Synergy с Spree 0.70.3

### ISSUE THREAD

**Issue by rubywazza** [ohmycto/synergy#20]
Привет!
При установке Synergy, выходит ошибка 
"Don't know how to build task 'rake spree:install'" на шаге:
rake spree:install

Выполнил: 
rake -T
действительно нет такой команды. Вот все что вывелось относительно spree:

rake spree:assets:relocate_images                 # Relocates files from public/assets directory
rake spree:assets:sync_images                     # Copies images from all app/assets directories into public/assets
rake spree:extensions:promotions:update           # Copies public assets of the Promotions to the instance public/ directory.
rake spree:reset_taxon_permalinks                 # Resets all taxon permalinks
rake spree:sync                                   # Synchronize public assets, migrations, seed and sample data from the Spree gems
rake spree_address_book:install:migrations        # Copy migrations from spree_address_book to application
rake spree_api:install:migrations                 # Copy migrations from spree_api to application
rake spree_auth:install:migrations                # Copy migrations from spree_auth to application
rake spree_core:install:migrations                # Copy migrations from spree_core to application
rake spree_i18n:new                               # Create a new translation file based on en
rake spree_i18n:stats                             # Show translation status for all supported locales other than en.
rake spree_i18n:sync                              # Syncronize translation files with latest en (adds comments with fallback en value)
rake spree_i18n:update_default                    # Update by retrieving the latest Spree locale fils
rake spree_promo:install:migrations               # Copy migrations from spree_promo to application
rake spree_sample:load                            # Loads sample data
rake spree_static_content:install:migrations      # Copy migrations from spree_static_content to application
rake spree_yandex_market:generate_torg_mail_ru    # Generate Torg.mail.ru export file
rake spree_yandex_market:generate_ym              # Generate Yandex.Market export file
rake spree_yandex_market:install:migrations       # Copy migrations from spree_yandex_market to application
rake spree_yandex_market:update                   # Copies public assets of the Yandex Market to the instance public/ directory.

Ставил на rails 3.1.3 и база данных MySQL с адаптером mysql2.

**Comment by ohmycto** [comment]
Вы используете последовательность команд от 0.60 для установки 0.70.

Советуем прочитать раздел Installation гема Spree: https://github.com/spree/spree
