### ISSUE TITLE
Несовместимости

### ISSUE THREAD

**Issue by valachi** [ohmycto/synergy#27]
Описание установки в readme абсолютно нереальное. При bundle install выдается куча несовместимостей. Начиная с того, что не найден synergy '~> 0.7.0' и кончая тем, что spree_i18n зависит от gem spree > 1.0
Проект еще жив? Если да, то обновите readme

**Comment by ohmycto** [comment]
Добрый день. Действительно до readme в master-ветке руки не дошли. Но это Open Source проект, приветствуется любая помощь, так что ждем от Вас pull request с нужной версией readme ;-)

**Comment by ohmycto** [comment]
Выделили ветку '0-70-stable' для версии 0.70 и обновили Readme в ней. Теперь все ставится по Readme нормально. https://github.com/secoint/synergy/tree/0-70-stable

**Comment by tvovochka** [comment]
Пытаюсь установить согласно инструкции из ветки '0-70-stable', но сталкиваюсь с ошибкой при выполнении команды "rake db:seed db:sample": 
rake aborted!
Don't know how to build task 'db:sample'
Проверяю, действительно у rake нет команды db:sample. Видимо от старой версии spree осталась и сейчас не работает.
Также после запуска проекта в браузере получаю ошибку:
Mysql2::Error: Table 'synergydb.pages' doesn't exist: SHOW FIELDS FROM `pages`

**Comment by ohmycto** [comment]
На вскидку сказать сложно, в качестве быстрого фикса просто уберите это 'db:sample' из команды. Все, что она делает - заполняет магазин тестовыми данными (учетками и заказами).

**Comment by tvovochka** [comment]
Если я правильно понимаю, то rake db:sample нужно заменить новой командой spree: 
bundle exec rake spree_sample:load

**Comment by ghost** [comment]
Устанавливается все без проблем, но, к сожалению, так же ошибка: Mysql2::Error: Table 'synergydb.pages' doesn't exist: SHOW FIELDS FROM pages
Таблицы pages в базе нет.

**Comment by ohmycto** [comment]
Прошу прощения, в предыдущем ответе я плохо вник в вопрос. @tvovochka попробуйте выполнить: 

rails g spree_static_content:install

**Comment by tvovochka** [comment]
Устанавливаю все по инструкции из ветки '0-70-stable':

bundle install
rails g spree:site
rails g spree_static_content:install
rails g spree_editor:install
rails g spree_address_book:install
rails g synergy:install
rake db:migrate
rake db:seed db:sample
rails s

На этапе установки "rails g spree_static_content:install" происходит миграция всех таблиц spree, кроме таблиц самого spree_static_content. При повторном вводе команды, уже никаких миграций не происходит. Таблицы pages в базе нет.

Вручную скопировал миграции из гема spree_static_content и запустил миграцию. Таблица pages появилась в базе, сайт запустился, но в результате получил сильно покареженный дизайн, из-за чего сложно разобраться что к чему.

В общем, на данный момент, порог вхождения в проект довольно высокий - нужно иметь не слабые навыки по работе с гемами просто для того чтобы увидеть главную страницу, что конечно отталкивает от такого перспективного проекта.
