### ISSUE TITLE
Проблема после установки

### ISSUE THREAD

**Issue by ghost** [ohmycto/synergy#28]
Установка была совершена полностью по README 0-70-stable.
После запуска постоянная ошибка:

 ActiveRecord::StatementInvalid in HomeController#index

Mysql2::Error: Table 'synergy_db.pages' doesn't exist: SHOW FIELDS FROM `pages`

Таблицы pages в базе нет.

**Comment by ohmycto** [comment]
Таблица pages появляется в результате установки расширения spree_static_content, которое входит в состав Synergy. Попробуйте выполнить:

rails g spree_static_content:install

По результатам отпишитесь, если помогло - внесем в Readme этот шаг.

**Comment by ghost** [comment]
В Readme есть этот шаг. Но он так же не создает таблицу pages. Вот список таблиц в базе сразу после шага 
rails g spree_static_content:install

mysql> show tables;
+-----------------------------+
| Tables_in_synergy_db        |
+-----------------------------+
| activators                  |
| addresses                   |
| adjustments                 |
| assets                      |
| calculators                 |
| configurations              |
| countries                   |
| creditcards                 |
| gateways                    |
| inventory_units             |
| line_items                  |
| log_entries                 |
| mail_methods                |
| option_types                |
| option_types_prototypes     |
| option_values               |
| option_values_variants      |
| orders                      |
| payment_methods             |
| payments                    |
| pending_promotions          |
| preferences                 |
| product_groups              |
| product_groups_products     |
| product_option_types        |
| product_properties          |
| product_scopes              |
| products                    |
| products_promotion_rules    |
| products_taxons             |
| promotion_action_line_items |
| promotion_actions           |
| promotion_rules             |
| promotion_rules_users       |
| properties                  |
| properties_prototypes       |
| prototypes                  |
| return_authorizations       |
| roles                       |
| roles_users                 |
| schema_migrations           |
| shipments                   |
| shipping_categories         |
| shipping_methods            |
| state_events                |
| states                      |
| tax_categories              |
| tax_rates                   |
| taxonomies                  |
| taxons                      |
| tokenized_permissions       |
| trackers                    |
| users                       |
| variants                    |
| zone_members                |
| zones                       |
+-----------------------------+

**Comment by Timopheym** [comment]
У меня таже проблема.
p.s. Использую sqllite

Processing by HomeController#index as HTML
Completed 500 Internal Server Error in 9ms

ActiveRecord::StatementInvalid (Could not find table 'pages'):

Rendered /usr/local/rvm/gems/ruby-1.9.3-p194@rails313/gems/actionpack-3.1.3/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.7ms)
Rendered /usr/local/rvm/gems/ruby-1.9.3-p194@rails313/gems/actionpack-3.1.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.3ms)
Rendered /usr/local/rvm/gems/ruby-1.9.3-p194@rails313/gems/actionpack-3.1.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (5.9ms)

**Comment by AKovtunov** [comment]
Тоже самое.

**Comment by LyriD** [comment]
аналогично(

**Comment by LyriD** [comment]
как я понимаю проблема с invalid byte sequence in UTF-8 во время выполнения миграций. вопрос как пофиксить открыт.

**Comment by ohmycto** [comment]
Проблема скорее всего в том, что вы пытаетесь запустить Synergy 0.70 на Ruby 1.9.3, в то время как рекомендованной версией Ruby для нее является REE.

На 1.9.3 можно запустить, но требуются определенные доработки напильником.

Рекомендую либо взять REE, либо подождать Synergy 1.3 (Ruby 1.9.3, Rails 3.2), которая должна появиться в течение месяца.

**Comment by LyriD** [comment]
нет, проблема не в этом. запустил под ree. не помогло

**Comment by ohmycto** [comment]
Насчет таблицы pages решение такое:
1. Добавить в конец Gemfile строку:
gem 'spree_static_content', :git => 'https://github.com/spree/spree_static_content.git', :branch => '0-70-stable'
2. bundle install
3. rails g spree_static_content:install
4. rake db:migrate

Нужная таблица появится.

**Comment by LyriD** [comment]
сработало, спасибо)
