### ISSUE TITLE
undefined local variable or method `current_user' for #<Spree::CheckoutController:0x007fc60d3ec238>

### ISSUE THREAD

**Issue by babrovka** [ohmycto/synergy#31]
Добрй день, 
следовал инструкциям
https://github.com/secoint/synergy/tree/1-3-x

При чекауте, после заполнения адреса и т.д получаю:

undefined local variable or method `current_user' for #Spree::CheckoutController:0x007fc60d3ec238

gemfile

source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'synergy', :git => 'git://github.com/secoint/synergy.git', :branch => '1-3-x'
gem 'spree_auth_devise', :git => 'git://github.com/spree/spree_auth_devise', :branch => '1-3-stable'
gem 'spree_i18n', :git => 'git://github.com/secoint/spree_i18n.git', :branch => '1-3-stable'
gem 'spree_static_content', :git => 'git://github.com/spree/spree_static_content.git', :branch => '1-3-stable'
gem 'spree_editor', :git => 'git://github.com/secoint/spree_editor.git'
gem 'spree_online_support', :git => 'git://github.com/secoint/spree_online_support.git'
gem 'spree_address_book', :git => 'git://github.com/romul/spree_address_book.git'

**Comment by bob-frost** [comment]
Ошибка в геме spree_address_book https://github.com/romul/spree_address_book/pull/56. До тех пор пока в нем не заменят метод current_user на spree_current_user можно использовать следующие временные решения:

1) использовать более старую версию spree_auth_devise:

`gem 'spree_auth_devise', :git => 'git://github.com/spree/spree_auth_devise', :ref => '877ceb93c313d3aa73ca4e1ee0e2fd5cbf669753'`

Но в моем случае это привело к ошибке `Bundler could not find compatible versions for gem "devise"` https://github.com/spree/spree_auth_devise/issues/80, которая пофиксана в более поздних коммитах. Можно решить, добавив в Gemfile

`gem 'devise', '2.2.3'`

2) использовать этот форк spree_address_book

`gem 'spree_address_book', :git => 'git://github.com/bob-frost/spree_address_book.git'`
