### ISSUE TITLE
Не устанавливается зависимости

### ISSUE THREAD

**Issue by glafir** [ohmycto/synergy#34]
Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_i18n (>= 0) ruby depends on
      spree_core (~> 3.1.0.beta) ruby
Could not find gem 'spree_core (~> 3.1.0.beta) ruby', which is required
by gem 'spree_i18n (>= 0) ruby', in any of the sources.

**Comment by glafir** [comment]
Or this

Bundler could not find compatible versions for gem
"spree_address_book":
  In Gemfile:
    synergy (>= 0) ruby depends on
      spree_address_book (~> 1.3.0) ruby

```
spree_address_book (>= 0) ruby
```

Could not find gem 'spree_address_book (~> 1.3.0) ruby', which is
required by gem 'synergy (>= 0) ruby', in any of the sources.

**Comment by andyvesel** [comment]
Тот же случай:
`Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_i18n (>= 0) ruby depends on
      spree_core (~> 3.1.0.beta) ruby
Could not find gem 'spree_core (~> 3.1.0.beta) ruby', which is required by gem
'spree_i18n (>= 0) ruby', in any of the sources.`

**Comment by ohmycto** [comment]
Прочитайте Readme пожалуйста. Данный гем совместим только со Spree 0.70, более свежие версии не поддерживаются.
