### ISSUE TITLE
Проблемы при установке

### ISSUE THREAD

**Issue by OlegPasko** [ohmycto/synergy#4]
Салют! Не могу установить, когда ввожу rails g spree:site -f выдает такое:
←[31mgit://github.com/yaroslav/russian.git (at master) is not checked out. Please run `bundle install`
В чем может быть проблема?  :(

ps. Тот же оригинальный спри встал без проблем, а тут такое (

**Comment by romul** [comment]
> В чем может быть проблема?

В сообщении об ошибке написано о том, что был пропущен шаг "bundle install"

**Comment by OlegPasko** [comment]
Да читать, вроде бы, умею. "bundle install" делал... создавал новое приложение, делал до, делал после. Проблема явно не в этом. Установить делал попыток пять.

**Comment by ohmycto** [comment]
> Да читать, вроде бы, умею. "bundle install" делал

В таком случае надо детальнее описывать проблему.
Возможно не установлен git и из-за этого "is not checked out".

**Comment by Sashe** [comment]
А у меня тоже на этом шаге ошибка, но другая

C:\Sites\synergy_app>rails g spree:site -f

```
D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require': 127: ═х эрщфхэр єърчрээр  яЁюЎхфєЁр.   - Init_nokogiri (LoadError)
D:/Ruby192/lib/ruby/gems/1.9.1/gems/nokogiri-1.4.4-x86-mingw32/lib/nokogiri/1.9/nokogiri.so
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `block in require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/nokogiri-1.4.4-x86-mingw32/lib/nokogiri/nokogiri.rb:1:in `<top (required)>'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `block in require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/nokogiri-1.4.4-x86-mingw32/lib/nokogiri.rb:13:in `<top (required)>'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `block in require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/synergy-0.50.0/app/controllers/admin/products_controller_decorator.rb:3:in `block in <top (required)>'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/synergy-0.50.0/app/controllers/admin/products_controller_decorator.rb:2:in `class_eval'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/synergy-0.50.0/app/controllers/admin/products_controller_decorator.rb:2:in `<top (required)>'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:235:in `load'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:235:in `block in load'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:235:in `load'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/synergy-0.50.0/lib/synergy.rb:13:in `block in activate'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/synergy-0.50.0/lib/synergy.rb:12:in `glob'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/synergy-0.50.0/lib/synergy.rb:12:in `activate'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/callbacks.rb:480:in `_run_prepare_callbacks'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/actionpack-3.0.7/lib/action_dispatch/middleware/callbacks.rb:40:in `initialize'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:33:in `new'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:33:in `build'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:79:in `block in build'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:79:in `each'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:79:in `inject'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:79:in `build'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/application.rb:162:in `app'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/application/finisher.rb:35:in `block in <module:Finisher>'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/initializable.rb:25:in `instance_exec'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/initializable.rb:25:in `run'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/initializable.rb:50:in `block in run_initializers'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/initializable.rb:49:in `each'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/initializable.rb:49:in `run_initializers'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/application.rb:134:in `initialize!'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/application.rb:77:in `method_missing'
    from C:/Sites/synergy_app/config/environment.rb:5:in `<top (required)>'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `block in require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/application.rb:103:in `require_environment!'
    from D:/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/commands.rb:16:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Куда копать??

**Comment by romul** [comment]
> Куда копать?

@Sashe: копать в сторону проблем работы nokogiri под Windows на Ruby 1.9.2

Рекомендованное рабочее окружение:
- GNU/Linux
- Ruby EE
- MySQL 5.1.x
- ImageMagick
- Git

**Comment by Sashe** [comment]
Я пытался, только ни у кого такой проблемы не возникало, похоже...

**Comment by romul** [comment]
Ну, беглый поиск по строке "х эрщфхэр єърчрээр  яЁюЎхфєЁр" показывает, что она скорее всего является частью загрузочной секции виндовых dll, т.е. скорее всего проблема в битой dll. Я давно не использую Windows, поэтому уже забыл, это вообще нормально, что она пытается использовать nokogiri.so, а не какую-нибудь nokogiri.dll? Всё-таки ELF и PE - это не одно и то же.

**Comment by Sashe** [comment]
Хз, я в nix'ах не просто 0, а отрицательное число какое-то...
И что делать? при обновлении nokogiri до 1.4.5 отказывается работать 

C:\Sites\mystore>rake synergy:install
←[31mCould not find nokogiri-1.4.4-x86-mingw32 in any of the sources←[0m
←[33mRun `bundle install` to install missing gems.←[0m

Интересное кино - он требует именно mingw32, а виндовый гем - mswin32. Как победить?

**Comment by romul** [comment]
Попробуй скачать https://rubygems.org/downloads/nokogiri-1.4.4-x86-mingw32.gem и установить из локального файла:

```
gem install --local path_to_gem/nokogiri-1.4.4-x86-mingw32.gem
```

> И что делать?

Попробовать найти кого-нибудь, кто программирует на Ruby под Windows, хотя это задача не из лёгких...

**Comment by Sashe** [comment]
minigw32 ставится без проблем, только на нёй не работает...

**Comment by Sashe** [comment]
радикально решил вопрос - переехал на убунту :))
но грабли новые вылезли - вроде всё проходит, а при попытке зайти на http://localhost:3000/ имеем 
Mysql2::Error in ProductsController#index

Table 'mystore_development.pages' doesn't exist

Rails.root: /home/sashe/Sites/mystore

**Comment by OlegPasko** [comment]
Sashe, а MySQL запущен?

**Comment by Sashe** [comment]
да, миграции проходят.

**Comment by Sashe** [comment]
Потихоньку продвигаюсь, вроде все встало, и тут опять вилы - добавил продукт в админке, захожу в магазин - и на тебе:
Encoding::CompatibilityError in Products#index

Showing /usr/local/ruby/lib/ruby/gems/1.9.1/gems/synergy_default_theme-1.0.1/app/views/shared/_products.html.erb where line #26 raised:

incompatible character encodings: ASCII-8BIT and UTF-8

Extracted source (around line #26):

23:           <% if defined?(SpreeReviews) %>
24:             <div align="center" style="height: 15px;"><%= render 'shared/rating', :product => product %></div>
25:           <% end %>  
26:           <%= link_to raw("<span class='price selling'>#{product_price(product)}</span>"), product, :class => 'info' %>
27:         <% end %>
28:       </li>
29:     <% end %>

что делать?

**Comment by romul** [comment]
> что делать?

Ну во-первых, спасибо за найденную несовместимость с ruby 1.9.2, она, насколько я помню, уже даже исправлена в master, т.е. можете попробовать подключить `gem 'synergy', :git => 'git://github.com/secoint/synergy.git'` и сделать `bundle update synergy` и `rake synergy:install db:migrate`
А во-вторых, почему Вы так усиленно избегаете рекомендованного рабочего окружения? Убунту - это уже хорошо, но рекомендованная версия Ruby - [Ruby EE](http://www.rubyenterpriseedition.com/download.html#ubuntu), основанная на Ruby 1.8.7, плюс можно [RVM](https://rvm.beginrescueend.com/) поставить, чтобы иметь возможность переключаться между версиями Ruby.
Ниндзя, запускающие движок на Ruby 1.9.2+, PostgreSQL и прочем, безусловно приветствуются, но новичкам явно не стоит заниматься подобными экспериментами.

**Comment by Sashe** [comment]
Круто! Заработало! 
А  я не избегаю, я просто думал, что ЕЕ это типа последняя версия!
Спасибо, буду дальше разбираться!

А есть какой-нибудь туториал по кастомизации?

**Comment by romul** [comment]
> А есть какой-нибудь туториал по кастомизации?

Есть, но пока только на английском - http://spreecommerce.com/documentation/customization.html

**Comment by Sashe** [comment]
С таксонами проблема тоже из-за руби?

http://localhost:3000/admin/taxonomies

Showing /usr/local/ruby/lib/ruby/gems/1.9.1/gems/synergy_default_theme-1.0.1/app/views/admin/taxonomies/_list.html.erb where line #12 raised:

undefined method `comparable?' for #Taxonomy:0xa2a27b8

Extracted source (around line #12):

9:   <% for taxonomy in @taxonomies %>
10:     <tr id="<%= dom_id taxonomy %>">
11:       <td><%= taxonomy.name %></td>
12:       <td><%= icon('tick') if taxonomy.comparable? %></td>
13:       <td><%= icon('tick') if taxonomy.show_on_homepage? %></td>
14:       <td class="actions">
15:         <%= link_to_edit taxonomy.id %> &nbsp; <%= link_to_delete taxonomy %>

Trace of template inclusion: /usr/local/ruby/lib/ruby/gems/1.9.1/gems/spree_core-0.60.0/app/views/admin/taxonomies/index.html.erb

Rails.root: /home/sashe/Sites/synergy_app

**Comment by romul** [comment]
Нет, но это уже тоже исправлено: https://github.com/romul/synergy_default_theme/issues/1

**Comment by Sashe** [comment]
Спасибо! И с таксономиями проблема опять появилась, всё добавляется, но на фронте не отображаются, хотя галки стоят. при добавлении такой текст появляется 
translation missing: ru.taxonomy &quot;Категории&quot; был успешно обновлен!

и в админке при редактировании товара в разделе таксоны нет кнопки добавления таксонов

Руби обновил, ЕЕ поставил

**Comment by OlegPasko** [comment]
Господа, а позвольте поинтересоваться, есть ли в синерджи скидки в зависимости от количества заказываемого товара?
зы. очень хотелось бы потыцать админку без необходимости установки :)
ззы. на демке что то со стилями натворили, http://demo.synergycommerce.ru/ логотип влево уполз )

**Comment by Sashe** [comment]
Подскажите ещё, пожалуйста.
Вот читаю по кастомизации туториал, решил испробовать хотябы то, что там в примере описано, добавил require site_hooks.rb в начало spree_site.rb, в site_hooks.rb insert_before :homepage_products, :text => '<'h1>Welcome!<'/h1>' 
никакого эффекта, что делаю не так?

p.s. апострофы я поставил только в комментарии

**Comment by romul** [comment]
> И с таксономиями проблема опять появилась, всё добавляется, но на фронте не отображаются

А таксоны в этих таксономиях есть?

> Господа, а позвольте поинтересоваться, есть ли в синерджи скидки в зависимости от количества заказываемого товара?

В базовой версии есть скидки в зависимости от стоимости заказываемых товаров. От кол-ва это уже излишне специфично для базы.

> очень хотелось бы потыцать админку без необходимости установки :)

На этой неделе планируется новый релиз, а заодно и доступ к админке демо-версии.

>  insert_before :homepage_products, :text => '<'h1>Welcome!<'/h1>'  никакого эффекта, что делаю не так?

В Synergy используется кастомная главная страница, поэтому хука :homepage_products просто нет. Попробуй 

```
insert_before :sidebar, :text => '<h1>Welcome!</h1>' 
```

**Comment by Sashe** [comment]
Я всё равно чёто делаю не так...  Добавил require site_hooks.rb в начало spree_site.rb, в site_hooks.rb insert_before :sidebar, :text => '<'h1>Welcome!<'/h1>' . rails s не запускается 
rails s
/home/sashe/Sites/synergy_app/lib/spree_site.rb:1: undefined local variable or method `site_hooks' for main:Object (NameError)
    from /home/sashe/.rvm/gems/ree-1.8.7-2011.03@store/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in`require'
    from /home/sashe/.rvm/gems/ree-1.8.7-2011.03@store/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from /home/sashe/.rvm/gems/ree-1.8.7-2011.03@store/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /home/sashe/.rvm/gems/ree-1.8.7-2011.03@store/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /home/sashe/.rvm/gems/ree-1.8.7-2011.03@store/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /home/sashe/.rvm/gems/ree-1.8.7-2011.03@store/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from /home/sashe/Sites/synergy_app/config/application.rb:11
    from /home/sashe/.rvm/gems/ree-1.8.7-2011.03@store/gems/railties-3.0.7/lib/rails/commands.rb:28:in`require'
    from /home/sashe/.rvm/gems/ree-1.8.7-2011.03@store/gems/railties-3.0.7/lib/rails/commands.rb:28
    from /home/sashe/.rvm/gems/ree-1.8.7-2011.03@store/gems/railties-3.0.7/lib/rails/commands.rb:27:in `tap'
    from /home/sashe/.rvm/gems/ree-1.8.7-2011.03@store/gems/railties-3.0.7/lib/rails/commands.rb:27
    from script/rails:6:in`require'
    from script/rails:6

**Comment by romul** [comment]
А ты что прямо в коде написал `require site_hooks.rb`?  o_O
Должно быть `require "site_hooks"`, но это уже не относится ни к Spree, ни к Rails, это основы Ruby.

**Comment by Sashe** [comment]
Ага, прям в коде. Ну, я совсем начинающий.
Разобрался с этим вроде, только всё равно не могу понять, как, например, менять логотип, добавить картинку в шаблон сайта, ну и вообще менять что-то глобально, кроме текста. 

class SiteHooks < Spree::ThemeSupport::HookListener
insert_before :sidebar, :text => "<'h1>Welcome!<'/h1>"  - работает
remove :admin_tabs_yandex_market - не работает
remove :header_panel_logo - не работает
insert_after :inside_head, :text =>"<'h3> some tel number <'/h3>" - добавляет текст в левом верхнем углу, хоть insert_after, хоть insert_before
