### ISSUE TITLE
Yandex market import

### ISSUE THREAD

**Issue by jalkoby** [ohmycto/synergy#5]
Установил по вики приложение, сделал настройки в вкладке yandex market

Короткое название магазина: sapp
Полное наименование компании: Sapp tech
URL-адрес главной страницы магазина:    http://localhost:3000
Категория выгрузки:    Категории
Валюта:   RUR:1;USD:CBRF:3;EUR:CBRF:0.2;
Отбор товара:    Только товар который есть в наличии
Стоимость доставки по своему региону:   0 руб.
Ссылка на файл: http://localhost:3000/yandex_market/yandex_market.xml  
Выгружаемые свойства товара:  
Группа товаров\категория: prefix
Производитель: vendor
Модель: model
Код производителя: vendor_code
Страна-производитель: country_of_manufacturer
Есть официальная гарантия производителя: manufacturer_warranty
Тип продукции: wares_type

в разделе товары ввожу любой id и нажимаю импорт, выбивается ошибка 
Данные о товаре не удалось взять с Яндекс.Маркет, проверьте ID товара и наличие полной информации о нём по ссылке http://market.yandex.ru/model.xml?modelid=6976935

Еще одна ошибка вылезла при переходе в http://0.0.0.0:3000/admin/taxonomies

undefined method `comparable?' for #Taxonomy:0xcd89fe4

Список gem:
- abstract (1.0.0)
- actionmailer (3.0.7)
- actionpack (3.0.7)
- activemerchant (1.14.0)
- activemodel (3.0.7)
- activerecord (3.0.7)
- activeresource (3.0.7)
- activesupport (3.0.7)
- acts_as_list (0.1.2)
- arel (2.0.10)
- bcrypt-ruby (2.1.4)
- braintree (2.10.1)
- builder (2.1.2)
- bundler (1.0.10)
- cancan (1.6.4)
- dalli (1.0.5)
- devise (1.3.3)
- erubis (2.6.6)
- faker (0.9.5)
- highline (1.5.1)
- i18n (0.5.0)
- jquery-rails (0.2.6)
- json (1.5.1)
- mail (2.2.19)
- meta_search (1.0.5)
- mime-types (1.16)
- nested_set (1.6.4)
- nokogiri (1.4.4)
- orm_adapter (0.0.5)
- paperclip (2.3.8)
- polyglot (0.3.1)
- rack (1.2.3)
- rack-mount (0.6.14)
- rack-test (0.5.7)
- rails (3.0.7)
- railties (3.0.7)
- rake (0.9.2)
- rd_find_by_param (0.1.1)
- rd_resource_controller (1.0.1)
- rd_unobtrusive_date_picker (0.1.0)
- russian (0.2.7 57af7fe)
- spree (0.60.0)
- spree_address_book (0.50.1)
- spree_api (0.60.0)
- spree_auth (0.60.0)
- spree_core (0.60.0)
- spree_dash (0.60.0)
- spree_dynamic_sitemaps (0.50.1)
- spree_editor (0.50.0)
- spree_i18n (1.0.0 f8f65ad)
- spree_online_support (0.50.0)
- spree_promo (0.60.0)
- spree_robokassa (0.50.1)
- spree_sample (0.60.0)
- spree_static_content (0.40.2)
- spree_yandex_market (1.2.0)
- sqlite3 (1.3.3)
- state_machine (0.9.4)
- stringex (1.0.3)
- synergy (0.50.0)
- synergy_default_theme (1.0.1)
- thor (0.14.6)
- treetop (1.4.9)
- tzinfo (0.3.28)
- warden (1.0.4)
- will_paginate (3.0.pre2)

**Comment by romul** [comment]
1. Не нужно настраивать экспорт, чтобы работал импорт
2. Импорт не работает в связи с изменениями в формате выдачи Я.Маркет, новый формат будет учтён в очередной версии synergy, выход которой запланирован на следующую неделю
3. `undefined method 'comparable?'` - исправлено в master ветке synergy_default_theme

Кстати, ты можешь уже сейчас проверить работу edge-версии, вместо стабильных версий пропиши в Gemfile:

```
gem 'synergy', :git => 'git://github.com/secoint/synergy.git'
gem 'synergy_default_theme', :git => 'git://github.com/romul/synergy_default_theme.git'
```

И запусти `bundle install`
