### ISSUE TITLE
отображение таксономии на главной странице

### ISSUE THREAD

**Issue by jalkoby** [ohmycto/synergy#6]
В разделе настройки таксономии есть поставить галочку отображать на главной странице, он исчезает и наоборот

**Comment by romul** [comment]
Так и задумано, предполагается что на главной странице отображаются таксоны из таксономии, не привязанной к категориям товаров, например, "Спецпредложения", "Новинки", etc. Т.е. всё то, что чаще всего не надо отображать в боковом меню. Впрочем, это всего лишь поведение по умолчанию, при желании его можно переопределить.
