### ISSUE TITLE
Методы доставки не работают 

### ISSUE THREAD

**Issue by jalkoby** [ohmycto/synergy#8]
При переходе в методы доставки, выбивает ошибку
undefined method `name' for nil:NilClass

> 32:         <%- locals = {:shipping_method => shipping_method} %>
> 33:         <%= hook :admin_shipping_methods_index_rows, locals do %>
> 34:           <td><%= shipping_method.name %></td>
> 35:           <td><%= shipping_method.zone.name %></td>
> 36:           <td><%= shipping_method.calculator.description %></td>
> 37:           <td><%= shipping_method.display_on.blank? ? t('both') : t(shipping_method.display_on) %></td>
> 38:         <% end %>

**Comment by romul** [comment]
Скорее всего вы создали метод доставки без названия, для предотвращения подобных случаев уже добавлена валидация в Spree 0-60-stable

**Comment by jalkoby** [comment]
кроме тех что при установке создались, других доставок нет

**Comment by jalkoby** [comment]
было исправлено удалением всех стандартных доставок
